# Create by Stallone L. de Souza (@stallone-dev) - 2024 - License: CC0 1.0 Universal

@url = http://localhost:8080


# Access "basic" route
GET {{url}}/ HTTP/1.1

###
# Access "barApi" route
POST {{url}}/bar HTTP/1.1
Content-Type: "application/json"

{
        "user": "TESTER",
        "data": {"bbbb":"yyyy"}
}

###
# Access "fooApi" route
POST {{url}}/foo HTTP/1.1
Content-Type: "application/json"

{
        "user": "TESTER",
        "data": {"aaaaa":"zzzzz"}
}

###
# Get user log registry
get {{url}}/getlog/TESTER HTTP/1.1

